pipeline {
    agent any
    options {
        skipDefaultCheckout true
    }
    stages {
        stage('wololo') {
          steps {
            echo "wololo"
            checkout ([$class: "GitSCM",
                       branches: [[name: "${branchName}"]],
                       doGenerateSubmoduleConfigurations: false,
                       extensions: [],
                       submoduleCfg: [],
                       userRemoteConfigs: [[url: "${repoUrl}"]]])
              echo "${repoUrl}"
              echo "${branchName}"
          }
        }
        stage('dafuq') {
            echo "caralho"
              sh "sh wololo.sh"
        }
    }
}
